/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.ClienteController;
import Controller.EstoqueController;
import Controller.ItemVendaController;
import Controller.ProdutoController;
import Controller.VendaController;
import Models.Cliente;
import Models.ItemVenda;
import Models.Produto;
import Models.Venda;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.Validacoes;

/**
 *
 * @author Andrew Nascimento
 */


public class TelaVendas extends javax.swing.JFrame {

    /**
     * Creates new form TelaVendas
     */
    
        ItemVenda itemVenda;
        ArrayList<ItemVenda> listaItens = new ArrayList<>();; 
        Produto produto = new Produto();
        Venda venda = new Venda();
        
    public TelaVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoPesquisaCliente = new javax.swing.ButtonGroup();
        GrupoPesquisaProduto = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaFim = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        ValorTotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton7 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        PesquisaNome = new javax.swing.JRadioButton();
        PesquisaCpf = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        SelecionarQuantidade = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        PesquisaCod = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NomeDoCliente = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CpfDoCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 900));
        setPreferredSize(new java.awt.Dimension(1000, 900));

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vendas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TabelaFim.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        TabelaFim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Quantidade", "Preço"
            }
        ));
        jScrollPane2.setViewportView(TabelaFim);

        jButton3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButton3.setText("Finalizar Compra");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButton4.setText("Excluir item");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel10.setText("Valor Total:");

        ValorTotal.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        ValorTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel11.setText("Data da Venda:");

        jButton7.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButton7.setText("Voltar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(59, 59, 59)
                        .addComponent(ValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton7))
                .addGap(43, 43, 43))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        GrupoPesquisaCliente.add(PesquisaNome);

        GrupoPesquisaCliente.add(PesquisaCpf);

        jButton5.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButton5.setText("Pesquisar Cliente");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel5.setText("CPF:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel4.setText("Nome:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel7.setText("Filtar Clientes");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton5)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNome))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PesquisaNome)
                                .addComponent(PesquisaCpf))))
                    .addComponent(jLabel7))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PesquisaNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCpf)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(PesquisaCpf)))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome"
            }
        ));
        jScrollPane3.setViewportView(tabelaClientes);

        jButton6.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButton6.setText("Selecionar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(476, 100));

        tabelaProduto.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Preço", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(tabelaProduto);

        jButton2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButton2.setText("Adicionar Produto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel9.setText("Selecione a quantidade desejada:");

        SelecionarQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SelecionarQuantidadeFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(SelecionarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel9)
                    .addComponent(SelecionarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel2.setText("Cod:");

        GrupoPesquisaProduto.add(PesquisaCod);

        jButton1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButton1.setText("Pesquisar Produtos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel6.setText("Filtrar Produtos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addComponent(PesquisaCod))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PesquisaCod)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel8.setText("Cliente:");

        NomeDoCliente.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        NomeDoCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel12.setText("CPF:");

        CpfDoCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeDoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CpfDoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(29, 29, 29)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NomeDoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CpfDoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(PesquisaNome.isSelected() && !(txtNome.getText().equals(""))){
            ArrayList<Cliente> listaClientes = ClienteController.ConsultarClientesNome(txtNome.getText());
            
            DefaultTableModel modelTabelaClientes = new DefaultTableModel();
            modelTabelaClientes.addColumn("CPF");
            modelTabelaClientes.addColumn("Nome");
            tabelaClientes.setModel(modelTabelaClientes);

            modelTabelaClientes.setRowCount(0);

            for (Cliente c : listaClientes) {
                modelTabelaClientes.addRow(new Object[]{c.getCpf(),c.getNome()});
            }

            txtNome.setText("");
            txtCpf.setText("");             
        }else if(PesquisaCpf.isSelected() && !(txtCpf.getText().equals(""))){
           
            ArrayList<Cliente> listaClientes = ClienteController.ConsultarClienteCpf(txtCpf.getText());
            
            DefaultTableModel modelTabelClientes = new DefaultTableModel();
            modelTabelClientes.addColumn("CPF");
            modelTabelClientes.addColumn("Nome");
            tabelaClientes.setModel(modelTabelClientes);

            modelTabelClientes.setRowCount(0);

            
            for (Cliente c : listaClientes) {
                modelTabelClientes.addRow(new Object[]{c.getCpf(),c.getNome()});
            }
            
            
            txtNome.setText("");
            txtCpf.setText("");
        }else{
            ArrayList<Cliente> listaClientes = ClienteController.ConsultarClientes();
            
            DefaultTableModel modelTabelClientes = new DefaultTableModel();
            modelTabelClientes.addColumn("CPF");
            modelTabelClientes.addColumn("Nome");
            tabelaClientes.setModel(modelTabelClientes);

            modelTabelClientes.setRowCount(0);

            for (Cliente c : listaClientes) {
                modelTabelClientes.addRow(new Object[]{c.getCpf(),c.getNome()});
            }

            txtNome.setText("");
            txtCpf.setText("");
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(tabelaClientes.getSelectedRow() != -1){
            int numeroLinha = tabelaClientes.getSelectedRow();
            
            String cpf = tabelaClientes.getModel().getValueAt(numeroLinha, 0).toString();
            String nome = tabelaClientes.getModel().getValueAt(numeroLinha, 1).toString();
            
            NomeDoCliente.setText(nome);
            CpfDoCliente.setText(cpf);
              
        }else{
            JOptionPane.showMessageDialog(this, "Selecione um cliente da tabela!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!(NomeDoCliente.getText().equals(""))){
            if(PesquisaCod.isSelected() && !(txtCod.getText().equals(""))){
           
                ArrayList<Produto> listaProdutos = ProdutoController.ConsultaProdutoCod(txtCod.getText());

                DefaultTableModel modelTabelProduto = new DefaultTableModel();
                modelTabelProduto.addColumn("Cod");
                modelTabelProduto.addColumn("Nome");
                modelTabelProduto.addColumn("Preço");
                modelTabelProduto.addColumn("Quantidade");
                tabelaProduto.setModel(modelTabelProduto);

                modelTabelProduto.setRowCount(0);


                for (Produto p : listaProdutos) {
                    modelTabelProduto.addRow(new Object[]{p.getCod(),p.getNome(),p.getPreco(), EstoqueController.PesquisaEstoque(p.getCod())});
                }


                txtNome.setText("");
                txtCod.setText("");
            }else{
                ArrayList<Produto> listaProdutos = ProdutoController.ConsultaProduto();

                DefaultTableModel modelTabelProduto = new DefaultTableModel();
                modelTabelProduto.addColumn("Cod");
                modelTabelProduto.addColumn("Nome");
                modelTabelProduto.addColumn("Preço");
                modelTabelProduto.addColumn("Quantidade");
                tabelaProduto.setModel(modelTabelProduto);

                modelTabelProduto.setRowCount(0);


                for (Produto p : listaProdutos) {
                    modelTabelProduto.addRow(new Object[]{p.getCod(),p.getNome(),p.getPreco(), EstoqueController.PesquisaEstoque(p.getCod())});
                }

                txtNome.setText("");
                txtCod.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Favor selecionar um cliente antes de continuar a compra");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(tabelaProduto.getSelectedRow() != -1){
            
            int numeroLinha = tabelaProduto.getSelectedRow();
            
            int cod = Integer.parseInt(tabelaProduto.getModel().getValueAt(numeroLinha, 0).toString());
            String nome = tabelaProduto.getModel().getValueAt(numeroLinha, 1).toString();
            String preco = tabelaProduto.getModel().getValueAt(numeroLinha, 2).toString();
            int quantidade = Integer.parseInt(tabelaProduto.getModel().getValueAt(numeroLinha, 3).toString());
            
           
            
            if(!(Validacoes.ValidarCampo(SelecionarQuantidade.getText()))){
                SelecionarQuantidade.setBackground(Color.red);
                return;
            }
            
            int verifica = Integer.parseInt(SelecionarQuantidade.getText());
            
            if(verifica > quantidade){
                JOptionPane.showMessageDialog(null, "Favor digitar um valor igual ou menor a quantidade no estoque");
                SelecionarQuantidade.setText("");
                return;
            }
            
            EstoqueController.ReduzirEstoque(cod, verifica);
            
            Produto p = new Produto();
            p.setCod(cod);
            p.setNome(nome);
            p.setPreco(Double.parseDouble(preco));
            
            ItemVendaController.Salvar(cod, Double.parseDouble(preco), verifica, p);
            
            ArrayList<Produto> listaProdutos = ProdutoController.ConsultaProduto();

            DefaultTableModel modelTabelProduto = new DefaultTableModel();
            modelTabelProduto.addColumn("Cod");
            modelTabelProduto.addColumn("Nome");
            modelTabelProduto.addColumn("Preço");
            modelTabelProduto.addColumn("Quantidade");
            tabelaProduto.setModel(modelTabelProduto);

            modelTabelProduto.setRowCount(0);


            for (Produto pro : listaProdutos) {
                modelTabelProduto.addRow(new Object[]{pro.getCod(),pro.getNome(),pro.getPreco(), EstoqueController.PesquisaEstoque(pro.getCod())});
            }
            
            ArrayList<ItemVenda> listaItens = ItemVendaController.ConsultaItens();
            
            DefaultTableModel modelTabelaItem = new DefaultTableModel();
            modelTabelaItem.addColumn("Cod_item");
            modelTabelaItem.addColumn("Cod");
            modelTabelaItem.addColumn("Nome");
            modelTabelaItem.addColumn("Quantidade");
            modelTabelaItem.addColumn("Preço");
            TabelaFim.setModel(modelTabelaItem);
            TabelaFim.removeColumn(TabelaFim.getColumnModel().getColumn(0));

            modelTabelaItem.setRowCount(0);

            double total = 0;
            for (ItemVenda item : listaItens) {
                modelTabelaItem.addRow(new Object[]{item.getCod_ItemVenda(), item.getProduto().getCod(),item.getProduto().getNome(),item.getQuantidade(), item.getPreco()});
                total += item.getPreco();
            }
            
            ValorTotal.setText(Validacoes.DecimalFormatado(total));
            
            
      
            /**itemVenda.setPreco(preco);
            itemVenda.setProduto(produto);
            itemVenda.setQuantidade(verifica);
            listaItens.add(itemVenda);
                
            DefaultTableModel modelTabelProduto = new DefaultTableModel();
            modelTabelProduto.addColumn("Cod");
            modelTabelProduto.addColumn("Nome");
            modelTabelProduto.addColumn("Preço");
            modelTabelProduto.addColumn("Quantidade");
            TabelaFim.setModel(modelTabelProduto);
            modelTabelProduto.addRow(new Object[]{produto.getCod(),produto.getNome(),produto.getPreco(), verifica});

            Date data = new Date();
            data = PainelData.getDate();

            ArrayList<Cliente> listaClientes = ClienteController.ConsultarClientesNome(NomeDoCliente.getText());

            venda.setCliente(listaClientes.get(0));
            venda.setItemVenda(listaItens);
            venda.setDataVenda((java.sql.Date) data);
            ValorTotal.setText(Double.toString(venda.getPrecoTotal()));
            
            **/
        }else{
            JOptionPane.showMessageDialog(this, "Selecione um produto da tabela!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Date data;
        
        if(!(Validacoes.ValidarCampoData(jDateChooser1.getDate()))){
            jDateChooser1.setBackground(Color.red);
            return;
        }else{
            data = jDateChooser1.getDate();
        }
        
        ArrayList<Cliente> listaClientes = ClienteController.ConsultarClienteCpf(CpfDoCliente.getText());
        
        if(VendaController.Salvar(listaClientes.get(0), data)){
            JOptionPane.showMessageDialog(null, "Venda Efetuada com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            ItemVendaController.Excluir();
            
            txtNome.setText("");
            txtCpf.setText("");
            txtCod.setText("");
            SelecionarQuantidade.setText("");
            ValorTotal.setText("");
            GrupoPesquisaCliente.clearSelection();
            GrupoPesquisaProduto.clearSelection();
            NomeDoCliente.setText("");
            CpfDoCliente.setText("");
            
            DefaultTableModel modelTabelaClientes = new DefaultTableModel();
            modelTabelaClientes.addColumn("CPF");
            modelTabelaClientes.addColumn("Nome");
            tabelaClientes.setModel(modelTabelaClientes);
            
            DefaultTableModel modelTabelProduto = new DefaultTableModel();
            modelTabelProduto.addColumn("Cod");
            modelTabelProduto.addColumn("Nome");
            modelTabelProduto.addColumn("Preço");
            modelTabelProduto.addColumn("Quantidade");
            tabelaProduto.setModel(modelTabelProduto);
            
            
            DefaultTableModel modelTabelaItem = new DefaultTableModel();
            modelTabelaItem.addColumn("Cod_item");
            modelTabelaItem.addColumn("Cod");
            modelTabelaItem.addColumn("Nome");
            modelTabelaItem.addColumn("Quantidade");
            modelTabelaItem.addColumn("Preço");
            TabelaFim.setModel(modelTabelaItem);
            TabelaFim.removeColumn(TabelaFim.getColumnModel().getColumn(0));
            
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao efetuar a venda", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(TabelaFim.getSelectedRow() != -1){
            int numeroLinha = TabelaFim.getSelectedRow();
            
            int cod_item = Integer.parseInt(TabelaFim.getModel().getValueAt(numeroLinha, 0).toString());
            int cod = Integer.parseInt(TabelaFim.getModel().getValueAt(numeroLinha, 1).toString());
            int quantidade = Integer.parseInt(TabelaFim.getModel().getValueAt(numeroLinha, 3).toString());
            
            boolean retorno = ItemVendaController.ExcluirEspecifico(cod_item);
            
            if(retorno){
                ArrayList<ItemVenda> listaItens = ItemVendaController.ConsultaItens();
            
                DefaultTableModel modelTabelaItem = new DefaultTableModel();
                modelTabelaItem.addColumn("Cod_item");
                modelTabelaItem.addColumn("Cod");
                modelTabelaItem.addColumn("Nome");
                modelTabelaItem.addColumn("Quantidade");
                modelTabelaItem.addColumn("Preço");
                TabelaFim.setModel(modelTabelaItem);
                TabelaFim.removeColumn(TabelaFim.getColumnModel().getColumn(0));

                modelTabelaItem.setRowCount(0);

                double total = 0;
                for (ItemVenda item : listaItens) {
                    modelTabelaItem.addRow(new Object[]{item.getCod_ItemVenda(), item.getProduto().getCod(),item.getProduto().getNome(),item.getQuantidade(), item.getPreco()});
                    total += item.getPreco();
                }
                ValorTotal.setText(Validacoes.DecimalFormatado(total));
                
                EstoqueController.AumentarEstoque(cod, quantidade);
                
                ArrayList<Produto> listaProdutos = ProdutoController.ConsultaProduto();

                DefaultTableModel modelTabelProduto = new DefaultTableModel();
                modelTabelProduto.addColumn("Cod");
                modelTabelProduto.addColumn("Nome");
                modelTabelProduto.addColumn("Preço");
                modelTabelProduto.addColumn("Quantidade");
                tabelaProduto.setModel(modelTabelProduto);

                modelTabelProduto.setRowCount(0);


                for (Produto pro : listaProdutos) {
                    modelTabelProduto.addRow(new Object[]{pro.getCod(),pro.getNome(),pro.getPreco(), EstoqueController.PesquisaEstoque(pro.getCod())});
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void SelecionarQuantidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SelecionarQuantidadeFocusGained
        SelecionarQuantidade.setBackground(Color.white);
    }//GEN-LAST:event_SelecionarQuantidadeFocusGained

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        TelaNavegacao telaNavegacao = new TelaNavegacao();
        telaNavegacao.setVisible(true);
        telaNavegacao.setLocationRelativeTo(null);
        
        for(int i = 0; i < TabelaFim.getRowCount(); i++){
            int cod = Integer.parseInt(TabelaFim.getModel().getValueAt(i, 1).toString());
            int quantidade = Integer.parseInt(TabelaFim.getModel().getValueAt(i, 3).toString());
            EstoqueController.AumentarEstoque(cod, quantidade);
        }
        
        ItemVendaController.Excluir();
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CpfDoCliente;
    private javax.swing.ButtonGroup GrupoPesquisaCliente;
    private javax.swing.ButtonGroup GrupoPesquisaProduto;
    private javax.swing.JLabel NomeDoCliente;
    private javax.swing.JRadioButton PesquisaCod;
    private javax.swing.JRadioButton PesquisaCpf;
    private javax.swing.JRadioButton PesquisaNome;
    private javax.swing.JTextField SelecionarQuantidade;
    private javax.swing.JTable TabelaFim;
    private javax.swing.JLabel ValorTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
